/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.presence;

import com.presence.common.koneksi;
import com.presence.common.userSession;
import com.presence.entities.absensi;
import com.presence.entities.kelompok_absensi;
import com.presence.entities.users;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.time.LocalDateTime;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author adw-ahad
 */
public class AbsensiKaryawan extends javax.swing.JPanel {

    /**
     * Creates new form AbsensiKaryawan
     */
    private boolean sudahAbsenMasuk = false;
    private boolean sudahAbsenKeluar = false;

    public AbsensiKaryawan() {
        initComponents();
        setOpaque(false);
        clock1.setClockColor(new Color(0, 0, 0));

        jPanel1.setLayout(new MigLayout());
//        jPanel1.add(jLabel5,"wrap");
        jPanel1.add(clock1, "align center top, gaptop 40,wrap");
        jPanel1.add(lbTanggal, "align center top,wrap");
        jPanel1.add(jPanel2, "align center top,gaptop 20,wrap");

        //unremark this if app is ready to demo
//        kelompok_absensi dataShift = getDataShift(userSession.getU_kelompokAbsen());
//        SimpleDateFormat s = new SimpleDateFormat("HH:mm");
//        String waktuMasuk = s.format(dataShift.getWaktu_masuk());
//        String waktuKeluar = s.format(dataShift.getWaktu_keluar());
//        lbShiftTime.setText(waktuMasuk + " s.d " + waktuKeluar);
//        lbShiftName.setText(dataShift.getNama());
        absensi dataAbsen = getDataAbsensi(userSession.getU_id());
        if (dataAbsen.getId() != 0) {
            if (dataAbsen.getWaktu_keluar() == null) {
                sudahAbsenMasuk = true;
                setButtonCheckinDisable();
            } else {
                sudahAbsenMasuk = true;
                sudahAbsenKeluar = true;

                setButtonCheckinDisable();
                setButtonCheckoutDisable();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        clock1 = new com.presence.component.Clock();
        lbTanggal = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbShiftName = new javax.swing.JLabel();
        lbShiftTime = new javax.swing.JLabel();
        btnCheckout = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnCheckin = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(244, 244, 244));

        lbTitle.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        lbTitle.setText("Absensi Karyawan");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lbTanggal.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lbTanggal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTanggal.setText("Thursday, 18 Agustus 2022");

        jPanel2.setBackground(new java.awt.Color(16, 108, 209));

        lbShiftName.setFont(new java.awt.Font("Segoe UI Black", 0, 16)); // NOI18N
        lbShiftName.setForeground(new java.awt.Color(255, 255, 255));
        lbShiftName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbShiftName.setText("Normal Shift");

        lbShiftTime.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lbShiftTime.setForeground(new java.awt.Color(255, 255, 255));
        lbShiftTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbShiftTime.setText("08:00 s.d 17.00");

        btnCheckout.setBackground(new java.awt.Color(255, 102, 102));
        btnCheckout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCheckout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCheckoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCheckoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCheckoutMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Absen Keluar");

        javax.swing.GroupLayout btnCheckoutLayout = new javax.swing.GroupLayout(btnCheckout);
        btnCheckout.setLayout(btnCheckoutLayout);
        btnCheckoutLayout.setHorizontalGroup(
            btnCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCheckoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnCheckoutLayout.setVerticalGroup(
            btnCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCheckoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnCheckin.setBackground(new java.awt.Color(0, 204, 102));
        btnCheckin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCheckin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCheckinMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCheckinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCheckinMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Absen Masuk");

        javax.swing.GroupLayout btnCheckinLayout = new javax.swing.GroupLayout(btnCheckin);
        btnCheckin.setLayout(btnCheckinLayout);
        btnCheckinLayout.setHorizontalGroup(
            btnCheckinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCheckinLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnCheckinLayout.setVerticalGroup(
            btnCheckinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCheckinLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(btnCheckin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 144, Short.MAX_VALUE))
                    .addComponent(lbShiftName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbShiftTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbShiftName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbShiftTime, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCheckout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCheckin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(clock1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbTanggal)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(clock1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbTitle)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckinMouseEntered
        // TODO add your handling code here:
        if (!sudahAbsenMasuk) {
            btnCheckin.setBackground(new Color(5, 168, 87));
        }
    }//GEN-LAST:event_btnCheckinMouseEntered

    private void btnCheckinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckinMouseExited
        // TODO add your handling code here:
        if (!sudahAbsenMasuk) {
            btnCheckin.setBackground(new Color(0, 204, 102));
        }
    }//GEN-LAST:event_btnCheckinMouseExited

    private void btnCheckoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckoutMouseEntered
        // TODO add your handling code here:
        if (!sudahAbsenKeluar) {
            btnCheckout.setBackground(new Color(235, 94, 94));
        }
    }//GEN-LAST:event_btnCheckoutMouseEntered

    private void btnCheckoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckoutMouseExited
        // TODO add your handling code here:
        if (!sudahAbsenKeluar) {
            btnCheckout.setBackground(new Color(255, 102, 102));
        }
    }//GEN-LAST:event_btnCheckoutMouseExited

    private void btnCheckinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckinMouseClicked
        // TODO add your handling code here:
        if (!sudahAbsenMasuk) {
            checkInAbsen();
            JOptionPane.showMessageDialog(null,
                    "Berhasil absen masuk hari ini!",
                    "Sukses",
                    JOptionPane.INFORMATION_MESSAGE);
            sudahAbsenMasuk = true;
            btnCheckin.setBackground(new Color(244, 244, 244));
            jLabel3.setForeground(new Color(194, 194, 194));
            btnCheckin.setEnabled(false);
        }
    }//GEN-LAST:event_btnCheckinMouseClicked

    private void btnCheckoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckoutMouseClicked
        // TODO add your handling code here:
        if (!sudahAbsenKeluar) {
            if (!sudahAbsenMasuk) {
                JOptionPane.showMessageDialog(null,
                        "Anda belum Absen Masuk hari ini, silakan klik absen masuk terlebih dahulu",
                        "Gagal",
                        JOptionPane.ERROR_MESSAGE);
            } else {
                checkOutAbsen();
                JOptionPane.showMessageDialog(null,
                        "Berhasil absen keluar hari ini!",
                        "Sukses",
                        JOptionPane.INFORMATION_MESSAGE);
                sudahAbsenKeluar = true;
                btnCheckout.setBackground(new Color(244, 244, 244));
                jLabel4.setForeground(new Color(194, 194, 194));
                btnCheckout.setEnabled(false);
            }
        }
    }//GEN-LAST:event_btnCheckoutMouseClicked

    private void setButtonCheckinDisable() {
        btnCheckin.setBackground(new Color(244, 244, 244));
        jLabel3.setForeground(new Color(194, 194, 194));
        btnCheckin.setEnabled(false);
    }

    private void setButtonCheckoutDisable() {
        btnCheckout.setBackground(new Color(244, 244, 244));
        jLabel4.setForeground(new Color(194, 194, 194));
        btnCheckout.setEnabled(false);
    }

    private absensi getDataAbsensi(int user_id) {
        absensi dataAbsensi = new absensi();
        try {
            Connection conn = new koneksi().connect();

            Statement st = conn.createStatement();
            String sql = "SELECT * FROM absensi WHERE user_id=? AND tanggal=curdate()";
            PreparedStatement preparedStatement = conn.prepareStatement(sql);
            preparedStatement.setInt(1, user_id);

            ResultSet rs = preparedStatement.executeQuery();
            if (rs.next()) {
                dataAbsensi.setTanggal(rs.getDate("tanggal"));
                dataAbsensi.setWaktu_masuk(rs.getObject("waktu_masuk", LocalDateTime.class));
                dataAbsensi.setWaktu_keluar(rs.getObject("waktu_keluar", LocalDateTime.class));
                dataAbsensi.setUser_id(rs.getInt("user_id"));
                dataAbsensi.setId(rs.getInt("id"));
            }
            st.close();
            conn.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null,
                    e.getMessage(),
                    "Gagal",
                    JOptionPane.ERROR_MESSAGE);

        }
        return dataAbsensi;
    }

    private kelompok_absensi getDataShift(int shift_id) {
        kelompok_absensi dataShift = new kelompok_absensi();
        try {
            Connection conn = new koneksi().connect();

            Statement st = conn.createStatement();
            String sql = "SELECT * FROM kelompok_absensi WHERE id=?";
            PreparedStatement preparedStatement = conn.prepareStatement(sql);
            preparedStatement.setInt(1, shift_id);

            ResultSet rs = preparedStatement.executeQuery();
            if (rs.next()) {
                dataShift.setNama(rs.getString("nama"));
                dataShift.setWaktu_masuk(rs.getTime("waktu_masuk"));
                dataShift.setWaktu_keluar(rs.getTime("waktu_keluar"));
            }
            st.close();
            conn.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null,
                    e.getMessage(),
                    "Gagal",
                    JOptionPane.ERROR_MESSAGE);
        }
        return dataShift;
    }

    private void checkInAbsen() {
        long timeNow = Calendar.getInstance().getTimeInMillis();
        java.sql.Timestamp ts = new java.sql.Timestamp(timeNow);
        try {
            Connection conn = new koneksi().connect();

            Statement st = conn.createStatement();
            String sql = "INSERT INTO absensi(user_id,waktu_masuk,tanggal) VALUES (?,?,?)";
            PreparedStatement preparedStatement = conn.prepareStatement(sql);
            preparedStatement.setInt(1, userSession.getU_id());
            preparedStatement.setTimestamp(2, ts);
            preparedStatement.setDate(3, java.sql.Date.valueOf(java.time.LocalDate.now()));

            preparedStatement.executeUpdate();

            st.close();
            conn.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null,
                    e.getMessage(),
                    "Gagal",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
    }

    private void checkOutAbsen() {
        long timeNow = Calendar.getInstance().getTimeInMillis();
        java.sql.Timestamp ts = new java.sql.Timestamp(timeNow);
        try {
            Connection conn = new koneksi().connect();

            Statement st = conn.createStatement();
            String sql = "UPDATE absensi set waktu_keluar = ? WHERE user_id=? AND tanggal=curdate()";
            PreparedStatement preparedStatement = conn.prepareStatement(sql);
            preparedStatement.setTimestamp(1, ts);
            preparedStatement.setInt(2, userSession.getU_id());

            preparedStatement.executeUpdate();

            st.close();
            conn.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null,
                    e.getMessage(),
                    "Gagal",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
    }

    @Override
    protected void paintComponent(Graphics grphcs) {
        Graphics2D g2 = (Graphics2D) grphcs;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(getBackground());
        g2.fillRect(0, 0, getWidth(), getHeight());
        super.paintComponent(grphcs);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnCheckin;
    private javax.swing.JPanel btnCheckout;
    private com.presence.component.Clock clock1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbShiftName;
    private javax.swing.JLabel lbShiftTime;
    private javax.swing.JLabel lbTanggal;
    private javax.swing.JLabel lbTitle;
    // End of variables declaration//GEN-END:variables
}
